name: CI GitOps IaC

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  terraform:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

  kubernetes:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Validar estrutura Kubernetes

        run: |

          test -f k8s/base/deployment.yaml

          test -f k8s/base/service.yaml

          test -f k8s/base/kustomization.yaml

          echo "Estrutura Kubernetes OK"

      - name: Política de segurança

        run: |

          if grep -R "NodePort" k8s/; then

            echo "NodePort não permitido"

            exit 1

          fi

          echo "Segurança aprovada"